SCHUNK-SE-Co-KG/schunk_egu_egk_gripper

schunk_egu_egk_gripper_dummy/README.md
schunk_egu_egk_gripper_dummy/config/__init__.py
schunk_egu_egk_gripper_dummy/setup.py
schunk_egu_egk_gripper_dummy/start_dummy

Update dummy dependencies

---

schunk_gripper_driver/launch/driver.launch.py
schunk_gripper_driver/package.xml
schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/test/test_services.py
schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/tests/test_behavior.py
schunk_gripper_library/tests/test_communication.py
schunk_gripper_library/tests/test_data_buffers.py
schunk_gripper_library/tests/test_threading.py

We need a high-level API that wraps all bit-related operations and module interaction as good as possible.
This will lead to a thin ROS2 driver wrapper.

Design highlevel API

---

schunk_gripper_library/schunk_gripper_library/utility.py
schunk_gripper_library/tests/test_scheduling.py

Industrial Modbus only supports a single client call at a time on the wire and requires careful synchronisation for dual-gripper setups. We'll use a priority queue for synchronized access.

Add a mechanism for task scheduling

---

schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/tests/test_behavior.py

- Weird behaviour when testing stop before absolute and relative movement. Needs to be looked into
- Might need to add ```use_gpe``` as a parameter

Add controlled stop

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_topics.py
schunk_gripper_interfaces/CMakeLists.txt
schunk_gripper_interfaces/msg/GripperState.msg

This will be high-level callers' access to low-level status information.

Publish the grippers' state as ROS2 topic

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/conftest.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_logging.py
schunk_gripper_library/schunk_gripper_library/driver.py

Minimal log footprint

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_services.py
schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/test_behavior.py

Run publishers concurrently

---

schunk_gripper_library/schunk_gripper_library/config/readable_parameters.json
schunk_gripper_library/schunk_gripper_library/config/writable_parameters.json
schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/test_communication.py

Fieldbuses have different endianness.
Do we need to consider this for _TCP/IP_ communication?
**Check**:
EtherCAT: little-endian?
EtherNet/IP: big-endian?
PROFINET: big-endian?
---

Support field buses

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_driver.py

A successful `configure` should guarantee users that they obtain an operational driver.
This wasn't the case before.

Fail `configure` with empty grippers list

---

.mypy.ini
schunk_gripper_dummy/schunk_gripper_dummy/dummy.py
schunk_gripper_dummy/schunk_gripper_dummy/tests/test_dummy.py
schunk_gripper_library/schunk_gripper_library/tests/test_behavior.py

The behavior tests were not really deterministic and failed from time to time. We really need to make this work.
---
Edit: The tests now run stable if we freshly restart the BKS simulator before each complete test run.
However, due to non-RT OS behavior, we cannot rely on the time computation for the _movement_-related commands to be exact like the real hardware guarantees us. We'll probably need to fix/adapt the general test concept here (different PR).

Fix behavior tests

---

schunk_gripper_library/schunk_gripper_library/driver.py

Use `max_vel` for the gripper's specification

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_driver.py

Fix `InvalidHandle` exceptions for timer callbacks

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_interfaces/msg/GripperSpec.msg
schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/test_communication.py

Enhance show_gripper_specification() by adding Modbus Device ID or IP-Address in specification

Improve gripper specification

---

schunk_gripper_driver/launch/driver.launch.py
schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_configuration.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_services.py

It would be nice to save the grippers' configuration and load that on the next startup. This feature targets automation where the configuration doesn't change after an initial setup, and where work needs to be resumed every morning.
**Possible interface**:
- `save_configuration()`
- `load_previous_configuration()`

Add mechanism to save config files

---

schunk_gripper_driver/schunk_gripper_driver/driver.py

Create gripper-specific services after `acknowledge`

---

schunk_gripper_driver/launch/driver.launch.py
schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/conftest.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_launch.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_parameters.py

Currently, when starting the driver with: ros2 launch schunk_gripper_driver driver.launch.py
A default gripper is created using serial port /dev/ttyUSB0 and device_id 12. 
This causes issues when:
Adding another gripper with device_id 12, which doesn’t override the default and causes configuration failure.
Adding a gripper with a different device_id (e.g. 14), which also fails because the driver still tries to connect to the default gripper with device_id 12.
---
Resolves #51

Resolve default gripper initialization with device_id 12 on start

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/conftest.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_services.py

Hide configuration-specific services after `on_configure`

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/conftest.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_services.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_topics.py
schunk_gripper_dummy/schunk_gripper_dummy/dummy.py
schunk_gripper_dummy/schunk_gripper_dummy/main.py
schunk_gripper_dummy/schunk_gripper_dummy/tests/test_dummy.py
schunk_gripper_dummy/schunk_gripper_dummy/tests/test_requests.py
schunk_gripper_dummy/schunk_gripper_dummy/tests/test_webserver.py
schunk_gripper_interfaces/CMakeLists.txt
schunk_gripper_interfaces/msg/ConnectionState.msg
schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/conftest.py
schunk_gripper_library/schunk_gripper_library/tests/etc/events.py
schunk_gripper_library/schunk_gripper_library/tests/test_reconnection.py

Grippers can lose their connection in the field, for instance due to cable breakage, power shortages, etc.
We need a clean method to automatically re-establish the connection to the loaded devices.
**Note**: This feature should be optional for industrial usage
The setup should
- automatically detect (partial) communication loss and react accordingly (per gripper)
- automatically re-connect with a _best effort_ strategy
- Publish the connection status to a respective topic (always)

Add a reconnection mechanism

---

schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/test_communication.py

The command received bit does not toggle when the plc output is cleared.
This means we can do that as the first step in each high-level method
and avoid possible race conditions when later waiting for the desired
bit set.
This race condition showed itself for very short methods, such as `stop_jogging`.

Robustify reading the command received bit

---

schunk_gripper_driver/schunk_gripper_driver/tests/conftest.py

We need a mechanism to test services with two (or more) distinct types.
This adds the `get_service_type` method to the `LifecycleInterface` instance that we use in most ROS2 system tests.
```python
def test_some_feature(lifecycle_interface):
driver = lifecycle_interface
node = Node("test_some_feature")
ServiceType= driver.get_service_type(
"/some/global/service/name"
)
client = node.create_client(
ServiceType,
"/some/global/service/name",
)
request = ServiceType.Request()
future = client.call_async(request)
rclpy.spin_until_future_complete(node, future)
```

Improve the test setup for getting dynamic service types

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_gpe_variants.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_services.py
schunk_gripper_interfaces/CMakeLists.txt
schunk_gripper_interfaces/srv/GripAtPosition.srv
schunk_gripper_interfaces/srv/GripAtPositionGPE.srv
schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/test_communication.py
schunk_gripper_library/schunk_gripper_library/tests/test_grip_commands.py

**Problem Statement**
The ROS 2 service currently includes all possible input fields including optional ones regardless of whether the connected gripper model supports them. This results in confusion for users and unclear interfaces, especially when some grippers do not support specific features.
We intend to separate the `GripAtPosition` and `GripAtPositionGPE` specific feature
**Steps:**

Support the `GripAtPosition` feature

---

schunk_gripper_driver/doc/Ethernet_WSL.md

This might be required for the driver's `scan` feature to work correctly on `WSL2` setups with Ubuntu.

Document port WSL2 forwarding

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_gpe_variants.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_services.py
schunk_gripper_interfaces/CMakeLists.txt
schunk_gripper_interfaces/srv/MoveToRelativePosition.srv
schunk_gripper_interfaces/srv/MoveToRelativePositionGPE.srv
schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/test_behavior.py
schunk_gripper_library/schunk_gripper_library/tests/test_communication.py
schunk_gripper_library/schunk_gripper_library/tests/test_control_operations.py

**Problem Statement:**
The ROS 2 service currently includes all possible input fields including optional ones regardless of whether the connected gipper model supports them. This results in confusion for users and unclear interfaces, especially when some grippers do not support specific features.
We intend to separate `MoveToRelativePosition` and `MoveToRelativePositionGPE` specific feature
**Steps:**

Support the `MoveToRelativePosition` feature

---

schunk_gripper_driver/schunk_gripper_driver/driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_configuration.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_driver.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_gpe_variants.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_headless_mode.py
schunk_gripper_driver/schunk_gripper_driver/tests/test_services.py
schunk_gripper_dummy/schunk_gripper_dummy/config/read_gripper_parameters.py
schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/test_communication.py
schunk_gripper_library/schunk_gripper_library/tests/test_module_update.py
schunk_gripper_library/schunk_gripper_library/tests/test_reconnection.py

When running in industrial settings, the ROS2 driver will start-up before the grippers are powered.
This means we need a mechanism that supports these (arbitrary long) delays and is operational once everything is up and in place.
- What should happen if only one of the previously saved grippers is responsive?
- What should happen if no gripper is responsive?
- What should the driver's _active_ state mean if not all grippers are functional?
- How can we distinguish between an unpowered but valid gripper and an erroneous entry in the saved configuration?
- Which gripper-specific services should be offered and in which state?
- Store the unique _gripper id_ (e.g. EGU_60_MB_N_B_1) in the configuration file and use that for further actions
- Support _configure_ and _activate_ even when some …

Support partial connects in headless mode

---

schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/test_reconnection.py

This used to crash the driver. It now works as expected.

Catch `IOError` when pulling the Modbus USB-RS485 cable

---

schunk_gripper_library/schunk_gripper_library/driver.py
schunk_gripper_library/schunk_gripper_library/tests/test_reconnection.py

This one occurred with a WSL and docker setup when starting in headless mode without pyhsical Ethernet connections.

Catch general `HTTPError`s in `connect()`
